apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: ligne-rouge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ligne-rouge
  template:
    metadata:
      labels:
        app: ligne-rouge
    spec:
      containers:
        - name: web
          image: martinez/ligne-rouge-web:latest
          ports:
            - containerPort: 80
        - name: db
          image: martinez/ligne-rouge-db:latest
          ports:
            - containerPort: 3306
